"""
Auto-Fix orchestration — locates the real source behind an accessibility
violation, asks Gemini for a minimal patch, applies it in a throwaway clone,
builds it, re-scans the built page to verify the violation is gone, and
pushes a branch with the verified fix.

Scope (MVP): one rule (button-name), one node, synchronous.
"""
import base64
import json
import logging
import os
import platform
import re
import shutil
import stat
import subprocess
import tempfile
import threading
import time
import urllib.error
import urllib.request
import uuid
from contextlib import contextmanager
from pathlib import Path
from queue import Empty, Queue

from config import Config

logger = logging.getLogger(__name__)

_GIT_TIMEOUT = 60
_NPM_INSTALL_TIMEOUT = 180
_NPM_BUILD_TIMEOUT = 120
_PREVIEW_START_TIMEOUT = 20

# Rules with a deterministic (non-AI) fallback fix — see _fallback_patch.
# Only patches actually generated by that mechanical path are eligible for
# auto-merge; a patch for one of these same rule ids generated by Gemini
# (once an API key is configured) is not, since AI output is less
# predictable and always deserves a human's review first.
RULES_WITH_FALLBACK = {
    "button-name", "image-alt", "label", "html-has-lang",
    "link-name", "heading-order", "color-contrast",
}

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

# On Windows, npm/npx are .cmd shims — subprocess won't resolve them without
# shell=True unless given the resolved path, which shutil.which does correctly
# on every platform.
NPM_CMD = shutil.which("npm") or "npm"
NPX_CMD = shutil.which("npx") or "npx"


def _run(args: list[str], cwd: Path, timeout: int) -> subprocess.CompletedProcess:
    return subprocess.run(args, cwd=cwd, check=True, capture_output=True, text=True, timeout=timeout)


def _rmtree_force(path: Path) -> None:
    """shutil.rmtree(ignore_errors=True) silently leaves git's read-only object files
    behind on Windows; clear the read-only bit and retry instead of leaking the temp dir."""
    def _on_error(func, target, exc_info):
        try:
            os.chmod(target, stat.S_IWRITE)
            func(target)
        except Exception:
            pass
    shutil.rmtree(path, onerror=_on_error)


def _kill_process_tree(proc: subprocess.Popen) -> None:
    """proc.terminate() only signals the immediate child — npx/vite/esbuild spawn
    grandchildren that survive it and leak. Kill the whole tree instead."""
    if platform.system() == "Windows":
        subprocess.run(["taskkill", "/PID", str(proc.pid), "/T", "/F"],
                        capture_output=True, timeout=10)
    else:
        import signal
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
        except Exception:
            proc.kill()
    try:
        proc.wait(timeout=5)
    except Exception:
        pass


def _git_auth_header(token: str) -> str:
    """GitHub's git-over-HTTPS wants Basic auth, not the Bearer scheme its REST API uses."""
    basic = base64.b64encode(f"x-access-token:{token}".encode()).decode()
    return f"http.extraHeader=AUTHORIZATION: basic {basic}"


def _clone_repo(repo_url: str, token: str, branch: str) -> Path:
    tmp_dir = Path(tempfile.mkdtemp(prefix="ada_autofix_"))
    _run(
        ["git", "-c", _git_auth_header(token),
         "clone", "--depth", "1", "--branch", branch, repo_url, str(tmp_dir)],
        cwd=tmp_dir.parent, timeout=_GIT_TIMEOUT,
    )
    return tmp_dir


def _grep_repo(repo_dir: Path, pattern: re.Pattern, extensions: tuple[str, ...] = (".jsx", ".tsx")) -> list[Path]:
    """Files (given extensions, skipping node_modules) whose content matches pattern."""
    hits = []
    for path in repo_dir.rglob("*"):
        if path.suffix not in extensions or "node_modules" in path.parts:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            continue
        if pattern.search(text):
            hits.append(path)
    return hits


def _locate_by_needle(repo_dir: Path, needle: re.Pattern, extensions: tuple[str, ...] = (".jsx", ".tsx")) -> tuple[str, int] | None:
    hits = _grep_repo(repo_dir, needle, extensions)
    if len(hits) != 1:
        return None
    path = hits[0]
    text = path.read_text(encoding="utf-8")
    # A file can be the only one that matches yet still contain the needle more
    # than once (two buttons with the same class, say) — taking the first hit
    # in that case would silently patch the wrong one, so require it unique here too.
    matches = list(needle.finditer(text))
    if len(matches) != 1:
        return None
    line_no = text[:matches[0].start()].count("\n") + 1
    return (path.relative_to(repo_dir).as_posix(), line_no)


def locate_source(repo_dir: Path, node_html: str, rule_id: str | None = None) -> tuple[str, int] | None:
    """
    Match a violation's outerHTML to a unique source file + line.

    `html-has-lang` is special-cased: the <html> tag lives in index.html, not
    a .jsx/.tsx component, so it needs its own file-type and needle.

    Otherwise tries the element's class name first (most specific signal). If
    it has no class attribute at all, falls back to the bare tag name — still
    safe, because a component rendered from a .map() (e.g. three <img>
    product cards) has exactly one source line for that tag regardless of
    which rendered instance triggered the violation, so "the only <img> in
    the repo" is still the correct place to fix. Never guesses across files:
    any ambiguity (zero or multiple matching files) returns None.
    """
    html = (node_html or "").strip()

    if rule_id == "html-has-lang":
        return _locate_by_needle(repo_dir, re.compile(r"<html[\s>]"), extensions=(".html",))

    if rule_id == "color-contrast":
        # The fix belongs in CSS, not the component — find the element's own
        # class selector rule block, not the JSX that references the class.
        class_match = re.search(r'class="([^"]+)"', html)
        if not class_match:
            return None
        class_name = class_match.group(1).strip().split()[0]
        needle = re.compile(re.escape(f".{class_name}") + r"\s*\{")
        return _locate_by_needle(repo_dir, needle, extensions=(".css",))

    class_match = re.search(r'class="([^"]+)"', html)
    if class_match:
        class_name = class_match.group(1).strip().split()[0]
        needle = re.compile(re.escape(f'className="{class_name}"'))
        return _locate_by_needle(repo_dir, needle)

    # No class — try other attributes next. Unlike className/htmlFor/tabIndex
    # etc, these are written identically in JSX and in the rendered DOM, so a
    # literal search for them is safe. Ordered roughly by how likely each is
    # to actually be unique.
    for attr in ("id", "aria-label", "name", "href", "src", "alt", "placeholder", "role"):
        attr_match = re.search(re.escape(attr) + r'="([^"]+)"', html)
        if not attr_match:
            continue
        needle = re.compile(re.escape(f'{attr}="{attr_match.group(1)}"'))
        located = _locate_by_needle(repo_dir, needle)
        if located:
            return located

    # Still nothing — try the element's own visible text (e.g. a heading or
    # button with no class or attributes at all, just a label). Skip anything
    # too short to be a safe signal on its own.
    text = re.sub(r"<[^>]+>", "", html).strip()
    if len(text) >= 3:
        located = _locate_by_needle(repo_dir, re.compile(re.escape(text)))
        if located:
            return located

    tag_match = re.match(r'<(\w+)', html)
    if not tag_match or tag_match.group(1).lower() in ("div", "span"):
        return None  # too generic a tag to safely treat as a unique signal
    tag = tag_match.group(1).lower()
    needle = re.compile(r"<" + re.escape(tag) + r"[\s/>]")
    return _locate_by_needle(repo_dir, needle)


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _relative_luminance(rgb: tuple[int, int, int]) -> float:
    def channel(c: int) -> float:
        c = c / 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (channel(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def _contrast_ratio(rgb1: tuple[int, int, int], rgb2: tuple[int, int, int]) -> float:
    l1, l2 = _relative_luminance(rgb1), _relative_luminance(rgb2)
    lighter, darker = max(l1, l2), min(l1, l2)
    return (lighter + 0.05) / (darker + 0.05)


def _adjust_to_ratio(fg_hex: str, bg_hex: str, target_ratio: float) -> str:
    """
    Move fg toward black or white (whichever increases contrast against bg,
    per the WCAG relative-luminance formula) until target_ratio is met.
    Preserves the original color as closely as possible — stops at the first
    step that satisfies the ratio rather than jumping straight to black/white.
    """
    fg_rgb, bg_rgb = _hex_to_rgb(fg_hex), _hex_to_rgb(bg_hex)
    target_rgb = (0, 0, 0) if _relative_luminance(bg_rgb) > 0.5 else (255, 255, 255)
    for step in range(1, 101):
        t = step / 100
        candidate = tuple(round(fg_rgb[i] + (target_rgb[i] - fg_rgb[i]) * t) for i in range(3))
        if _contrast_ratio(candidate, bg_rgb) >= target_ratio:
            return "#{:02x}{:02x}{:02x}".format(*candidate)
    return "#{:02x}{:02x}{:02x}".format(*target_rgb)


def _parse_contrast_data(node: dict) -> tuple[str, str, float] | None:
    """Extract (fg_hex, bg_hex, required_ratio) from an axe color-contrast node."""
    node = node or {}
    for check in node.get("any", []):
        data = check.get("data") or {}
        fg, bg = data.get("fgColor"), data.get("bgColor")
        if fg and bg:
            ratio_str = str(data.get("expectedContrastRatio", "4.5:1"))
            try:
                ratio = float(ratio_str.split(":")[0])
            except (ValueError, IndexError):
                ratio = 4.5
            return fg, bg, ratio

    summary = node.get("failureSummary", "") or ""
    fg_match = re.search(r"foreground color:\s*(#[0-9a-fA-F]{3,8})", summary)
    bg_match = re.search(r"background color:\s*(#[0-9a-fA-F]{3,8})", summary)
    if not fg_match or not bg_match:
        return None
    ratio_match = re.search(r"Expected contrast ratio of\s*([\d.]+):1", summary)
    ratio = float(ratio_match.group(1)) if ratio_match else 4.5
    return fg_match.group(1), bg_match.group(1), ratio


def _fallback_patch(rule: dict, node: dict, file_content: str) -> dict | None:
    """
    Deterministic placeholder fixes used only when GEMINI_API_KEY isn't configured —
    same idea as the existing /api/ai-fix mock fallback (app.py). These prove the rest
    of the pipeline works without needing a live Gemini call; the generated text is a
    generic/derived placeholder, not a real contextual label — add a real API key for that.
    """
    rule_id = rule.get("id")
    html = (node or {}).get("html", "")

    if rule_id == "button-name":
        class_match = re.search(r'class="([^"]+)"', html)
        if not class_match:
            return None
        class_name = class_match.group(1).strip().split()[0]
        pattern = re.compile(r'<button([^>]*\bclassName="' + re.escape(class_name) + r'"[^>]*?)(/?)>')
        m = pattern.search(file_content)
        if not m or "aria-label" in m.group(1):
            return None
        attrs, self_close = m.group(1).rstrip(), m.group(2)
        before = m.group(0)
        after = f'<button{attrs} aria-label="Menu"' + (' ' if self_close else '') + f'{self_close}>'
        return {"before": before, "after": after}

    if rule_id == "image-alt":
        # Derive alt text from the rendered src's filename (e.g. /jacket.svg -> "Jacket").
        # A real filename is at least a genuine, human-chosen signal, unlike a guess.
        src_match = re.search(r'src="([^"]+)"', html)
        alt_text = "Image"
        if src_match:
            filename = src_match.group(1).rsplit("/", 1)[-1]
            name = re.sub(r"\.\w+$", "", filename)
            name = re.sub(r"[-_]+", " ", name).strip()
            if name:
                alt_text = name.title()
        pattern = re.compile(r"<img([^>]*?)(/?)>")
        m = pattern.search(file_content)
        if not m or "alt=" in m.group(1):
            return None
        attrs, self_close = m.group(1).rstrip(), m.group(2)
        before = m.group(0)
        after = f'<img{attrs} alt="{alt_text}"' + (' ' if self_close else '') + f'{self_close}>'
        return {"before": before, "after": after}

    if rule_id == "label":
        # Derive aria-label from the specific input's own placeholder text — this
        # correctly targets the right one even when a file has several inputs.
        placeholder_match = re.search(r'placeholder="([^"]+)"', html)
        if not placeholder_match:
            return None
        placeholder = placeholder_match.group(1)
        tag_match = re.match(r"<(\w+)", html.strip())
        tag = tag_match.group(1) if tag_match else "input"
        pattern = re.compile(r"<" + re.escape(tag) + r"([^>]*?)(/?)>")
        for m in pattern.finditer(file_content):
            attrs = m.group(1)
            if f'placeholder="{placeholder}"' in attrs and "aria-label=" not in attrs:
                self_close = m.group(2)
                before = m.group(0)
                after = f'<{tag}{attrs.rstrip()} aria-label="{placeholder}"' + (' ' if self_close else '') + f'{self_close}>'
                return {"before": before, "after": after}
        return None

    if rule_id == "html-has-lang":
        # Always correct, no guessing needed: the site's own text content is English.
        pattern = re.compile(r"<html([^>]*?)(/?)>")
        m = pattern.search(file_content)
        if not m or "lang=" in m.group(1):
            return None
        attrs, self_close = m.group(1).rstrip(), m.group(2)
        before = m.group(0)
        after = f'<html{attrs} lang="en"' + (' ' if self_close else '') + f'{self_close}>'
        return {"before": before, "after": after}

    if rule_id == "link-name":
        # A generic accessible name (screen readers read aria-label over visible
        # text) — satisfies the rule mechanically without changing what's on screen.
        class_match = re.search(r'class="([^"]+)"', html)
        if not class_match:
            return None
        class_name = class_match.group(1).strip().split()[0]
        tag_match = re.match(r"<(\w+)", html.strip())
        tag = tag_match.group(1) if tag_match else "a"
        pattern = re.compile(r"<" + re.escape(tag) + r'([^>]*\bclassName="' + re.escape(class_name) + r'"[^>]*?)(/?)>')
        m = pattern.search(file_content)
        if not m or "aria-label" in m.group(1):
            return None
        attrs, self_close = m.group(1).rstrip(), m.group(2)
        before = m.group(0)
        after = f'<{tag}{attrs} aria-label="Learn more"' + (' ' if self_close else '') + f'{self_close}>'
        return {"before": before, "after": after}

    if rule_id == "heading-order":
        # Shift the heading down exactly one level (h3 -> h2, etc). This is a
        # best-effort guess at the *right* level without seeing the whole
        # document's heading structure, but low-risk: worst case it's still a
        # semantically reasonable heading level, easy for a reviewer to adjust.
        tag_match = re.match(r"<h([1-6])", html.strip())
        if not tag_match:
            return None
        level = int(tag_match.group(1))
        if level <= 1:
            return None
        old_tag, new_tag = f"h{level}", f"h{level - 1}"
        class_match = re.search(r'class="([^"]+)"', html)
        if class_match:
            class_name = class_match.group(1).strip().split()[0]
            body = r'<' + old_tag + r'([^>]*\bclassName="' + re.escape(class_name) + r'"[^>]*?)(/?)>(.*?)</' + old_tag + r'>'
        else:
            body = r"<" + old_tag + r"([^>]*?)(/?)>(.*?)</" + old_tag + r">"
        m = re.compile(body, re.DOTALL).search(file_content)
        if not m:
            return None
        attrs, self_close, inner = m.group(1), m.group(2), m.group(3)
        before = m.group(0)
        after = f"<{new_tag}{attrs}{self_close}>{inner}</{new_tag}>"
        return {"before": before, "after": after}

    if rule_id == "color-contrast":
        # Genuinely computable, not a guess: WCAG contrast is a defined formula.
        # Darken/lighten the exact foreground color axe reported until the
        # exact required ratio it reported is met.
        contrast_data = _parse_contrast_data(node or {})
        if not contrast_data:
            return None
        fg_hex, bg_hex, target_ratio = contrast_data
        new_fg = _adjust_to_ratio(fg_hex, bg_hex, target_ratio)
        pattern = re.compile(r"color:\s*" + re.escape(fg_hex), re.IGNORECASE)
        m = pattern.search(file_content)
        if not m:
            return None
        before = m.group(0)
        after = f"color: {new_fg}"
        return {"before": before, "after": after}

    return None


def generate_patch(rule: dict, node: dict, file_content: str) -> dict | None:
    """
    Ask Gemini for a verbatim before/after snippet. Returns None on any failure.
    Rules with a deterministic fallback always use it, key or no key — that's
    what keeps those auto-merge-eligible regardless of whether Gemini is configured.
    """
    rule_id = rule.get("id", "unknown")
    if rule_id in RULES_WITH_FALLBACK:
        return _fallback_patch(rule, node, file_content)
    if not Config.GEMINI_API_KEY:
        return None
    prompt = f"""You are fixing a web accessibility violation in a React (JSX) source file.

Violation: {rule_id} — {rule.get("help", "")}
Details: {rule.get("description", "")}
The offending rendered HTML: {(node or {}).get("html", "")}

Here is the full source file content:
---
{file_content}
---

Find the exact JSX element responsible for this violation and provide a minimal fix (e.g. add an aria-label). Respond with ONLY valid JSON in this exact shape, no other text:
{{
  "before": "the exact original lines from the file above that need to change, copied character-for-character including whitespace",
  "after": "the corrected replacement for those exact lines"
}}

The "before" value MUST be an exact substring of the file content given above — copy it verbatim, do not paraphrase or reformat it."""

    payload = json.dumps({
        "contents": [{"parts": [{"text": prompt}]}],
        # gemini-3.6-flash spends a chunk of this budget on hidden reasoning
        # before it ever writes the JSON answer — 800 was tuned for Claude,
        # which has no such step, and left real patches truncated to nothing.
        "generationConfig": {"maxOutputTokens": 4096},
    }).encode()
    req = urllib.request.Request(
        f"https://generativelanguage.googleapis.com/v1beta/models/{Config.GEMINI_MODEL}:generateContent"
        f"?key={Config.GEMINI_API_KEY}",
        data=payload,
        headers={"content-type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read())
        text = result["candidates"][0]["content"]["parts"][0]["text"].strip()
        text = text.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        patch = json.loads(text)
        if not patch.get("before") or not patch.get("after"):
            return None
        return {"before": patch["before"], "after": patch["after"]}
    except Exception:
        logger.exception("Auto-fix patch generation failed")
        return None


def validate_patch(file_content: str, before: str, after: str) -> bool:
    return (
        bool(before) and bool(after)
        and file_content.count(before) == 1
        and after != before
        and len(after) < len(before) + 500
    )


def run_tests(repo_dir: Path) -> dict:
    pkg_path = repo_dir / "package.json"
    try:
        pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    except Exception:
        return {"ran": False}
    if not pkg.get("scripts", {}).get("test"):
        return {"ran": False}
    try:
        proc = subprocess.run(
            [NPM_CMD, "test", "--silent"], cwd=repo_dir,
            capture_output=True, text=True, timeout=120,
        )
        return {"ran": True, "passed": proc.returncode == 0, "output": (proc.stdout + proc.stderr)[-2000:]}
    except Exception as e:
        return {"ran": True, "passed": False, "output": str(e)}


@contextmanager
def build_and_preview(repo_dir: Path):
    """npm install + build, then serve dist/ via `vite preview` and yield its URL."""
    _run([NPM_CMD, "install", "--silent"], cwd=repo_dir, timeout=_NPM_INSTALL_TIMEOUT)
    _run([NPM_CMD, "run", "build", "--silent"], cwd=repo_dir, timeout=_NPM_BUILD_TIMEOUT)

    proc = subprocess.Popen(
        [NPX_CMD, "vite", "preview", "--port", "0", "--strictPort"],
        cwd=repo_dir, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,
        start_new_session=(platform.system() != "Windows"),
    )
    # proc.stdout.readline() blocks with no timeout of its own, so a deadline check
    # between calls can't actually bound the wait — read on a background thread and
    # pull lines through a queue, which DOES support a real timeout.
    line_queue: "Queue[str | None]" = Queue()

    def _pump():
        for line in iter(proc.stdout.readline, ""):
            line_queue.put(line)
        line_queue.put(None)

    reader = threading.Thread(target=_pump, daemon=True)
    reader.start()

    preview_url = None
    try:
        deadline = time.time() + _PREVIEW_START_TIMEOUT
        while time.time() < deadline:
            try:
                line = line_queue.get(timeout=max(0.1, deadline - time.time()))
            except Empty:
                break
            if line is None:
                break
            match = re.search(r"(https?://localhost:\d+\S*)", _ANSI_RE.sub("", line))
            if match:
                preview_url = match.group(1)
                break
        if not preview_url:
            raise RuntimeError("vite preview did not report a URL in time")
        yield preview_url
    finally:
        _kill_process_tree(proc)


def rescan_and_verify(preview_url: str, rule_id: str) -> bool:
    from services.url_processor import process_url
    result = process_url(preview_url, write_output=False)
    violations = result.get("axeResult", {}).get("violations", [])
    return not any(v.get("id") == rule_id for v in violations)


def _parse_github_repo(repo_url: str) -> tuple[str, str] | None:
    match = re.match(r"https://github\.com/([\w.-]+)/([\w.-]+?)(?:\.git)?/?$", repo_url)
    return match.groups() if match else None


def push_branch(repo_dir: Path, branch_name: str, token: str, commit_message: str, repo_url: str) -> str:
    def git(*args, extra_headers=False):
        base = ["git"]
        if extra_headers:
            base += ["-c", _git_auth_header(token)]
        base += ["-c", "user.email=ada-bot@ada-tool.local", "-c", "user.name=ADA Auto-Fix"]
        _run(base + list(args), cwd=repo_dir, timeout=_GIT_TIMEOUT)

    git("checkout", "-b", branch_name)
    git("add", "-A")
    git("commit", "-m", commit_message)
    git("push", "origin", branch_name, extra_headers=True)

    parsed = _parse_github_repo(repo_url)
    if parsed:
        owner, repo = parsed
        return f"https://github.com/{owner}/{repo}/tree/{branch_name}"
    return branch_name


def _pr_body(rule: dict, node: dict, patch: dict, file_path: str, line_no: int) -> str:
    rule_id = rule.get("id", "")
    return f"""### Accessibility fix — `{rule_id}`

{rule.get("help", "")}

{rule.get("description", "")}

**File:** `{file_path}:{line_no}`

**Before**
```jsx
{patch["before"]}
```

**After**
```jsx
{patch["after"]}
```

---
Generated and verified by ADA Auto-Fix: the patch was applied in an isolated sandbox, built, and re-scanned to confirm this violation no longer occurs before this branch was pushed. Review before merging.
"""


def create_pull_request(repo_url: str, token: str, branch_name: str, base_branch: str,
                         title: str, body: str) -> dict | None:
    """Open a PR for an already-pushed branch. Returns {"url", "number"}, or None on any
    failure (e.g. a PR for this branch already exists) — a convenience step, not a gate."""
    parsed = _parse_github_repo(repo_url)
    if not parsed:
        return None
    owner, repo = parsed
    payload = json.dumps({"title": title, "head": branch_name, "base": base_branch, "body": body}).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{owner}/{repo}/pulls",
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "ADA-Accessibility-Intelligence",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read())
        if not result.get("html_url") or not result.get("number"):
            return None
        return {"url": result["html_url"], "number": result["number"]}
    except Exception:
        logger.exception("create_pull_request failed for %s/%s (%s)", owner, repo, branch_name)
        return None


def is_auto_merge_eligible(rule_id: str) -> bool:
    """
    True only for a patch that actually came from a deterministic fallback fix,
    never one generated by Gemini — AI output always needs human review.
    generate_patch() always routes these rule ids to the fallback, key or no
    key, so rule id alone is enough to know which path produced the patch.
    """
    return rule_id in RULES_WITH_FALLBACK


def merge_pull_request(repo_url: str, token: str, pr_number: int) -> bool:
    """Merge an already-open PR. Returns True only on a confirmed merge."""
    parsed = _parse_github_repo(repo_url)
    if not parsed:
        return False
    owner, repo = parsed
    payload = json.dumps({"merge_method": "merge"}).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/merge",
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "ADA-Accessibility-Intelligence",
            "Content-Type": "application/json",
        },
        method="PUT",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read())
        return bool(result.get("merged"))
    except Exception:
        logger.exception("merge_pull_request failed for %s/%s #%s", owner, repo, pr_number)
        return False


def is_pull_request_open(repo_url: str, token: str, pr_number: int) -> bool:
    """
    True only if GitHub currently reports this PR as open. Used to double-check
    a "duplicate" PR recorded in our own database — that record only reflects
    what happened when we opened it, not anything that happened to it on
    GitHub since (closed without merging, repo archived, etc). Any failure
    (PR deleted, repo inaccessible) is treated as "not open" so a stale local
    record can never permanently block re-running Auto-Fix on a violation.
    """
    parsed = _parse_github_repo(repo_url)
    if not parsed:
        return False
    owner, repo = parsed
    req = urllib.request.Request(
        f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "ADA-Accessibility-Intelligence",
        },
        method="GET",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read())
        return result.get("state") == "open"
    except Exception:
        return False


def run_auto_fix(link: dict, page_url: str, rule: dict, node: dict) -> dict:
    """Runs the full pipeline. `link` is a RepoLink dict from db.get_repo_link_for_url."""
    steps: list[dict] = []

    def step(name: str, ok: bool, detail: str = ""):
        steps.append({"name": name, "ok": ok, "detail": detail})

    repo_dir = None
    try:
        repo_dir = _clone_repo(link["repo_url"], link["access_token"], link["default_branch"])
        step("Clone repo", True)

        located = locate_source(repo_dir, (node or {}).get("html", ""), rule.get("id"))
        if not located:
            step("Locate source", False, "Could not uniquely match this violation to a source file")
            return {"status": "failed", "steps": steps, "error": steps[-1]["detail"]}
        file_path, line_no = located
        step("Locate source", True, f"{file_path}:{line_no}")

        full_path = repo_dir / file_path
        file_content = full_path.read_text(encoding="utf-8")

        patch = generate_patch(rule, node, file_content)
        if not patch:
            rule_id = rule.get("id")
            if rule_id in RULES_WITH_FALLBACK:
                detail = "Built-in fallback fix didn't match this violation's markup"
            elif not Config.GEMINI_API_KEY:
                detail = "No GEMINI_API_KEY configured — this rule has no built-in fallback fix without one"
            else:
                detail = "Gemini did not return a usable patch for this violation"
            step("Generate fix", False, detail)
            return {"status": "failed", "steps": steps, "error": steps[-1]["detail"]}
        step("Generate fix", True)

        if not validate_patch(file_content, patch["before"], patch["after"]):
            step("Validate patch", False, "Patch did not validate against the source file")
            return {"status": "failed", "steps": steps, "error": steps[-1]["detail"]}
        step("Validate patch", True)
        full_path.write_text(file_content.replace(patch["before"], patch["after"], 1), encoding="utf-8")

        test_result = run_tests(repo_dir)
        if test_result.get("ran") and not test_result.get("passed"):
            step("Run tests", False, "Existing tests failed after the patch")
            return {"status": "failed", "steps": steps, "error": steps[-1]["detail"]}
        step("Run tests", True, "no tests defined" if not test_result.get("ran") else "passed")

        try:
            with build_and_preview(repo_dir) as preview_url:
                step("Build", True)
                verified = rescan_and_verify(preview_url, rule.get("id", ""))
        except subprocess.CalledProcessError as e:
            step("Build", False, (e.stderr or str(e))[-500:])
            return {"status": "failed", "steps": steps, "error": "Build failed"}
        except Exception as e:
            step("Build", False, str(e))
            return {"status": "failed", "steps": steps, "error": "Build or re-scan failed"}

        if not verified:
            step("Re-scan", False, "Violation still present after the fix")
            return {"status": "failed", "steps": steps, "error": steps[-1]["detail"]}
        step("Re-scan", True, "violation resolved")

        rule_id = rule.get("id", "fix")
        branch_name = f"ada/fix/{rule_id}-{uuid.uuid4().hex[:8]}"
        branch_url = push_branch(
            repo_dir, branch_name, link["access_token"],
            f"ADA Auto-Fix: {rule.get('help', rule_id)}", link["repo_url"],
        )
        step("Push branch", True, branch_url)

        pr = create_pull_request(
            link["repo_url"], link["access_token"], branch_name, link["default_branch"],
            f"ADA Auto-Fix: {rule.get('help', rule_id)}",
            _pr_body(rule, node, patch, file_path, line_no),
        )
        step("Open PR", bool(pr), (pr["url"] if pr else "Branch pushed, but opening the PR failed — open it manually"))

        result = {"status": "verified", "steps": steps, "branch_url": branch_url}
        if pr:
            result["pr_url"] = pr["url"]
            if is_auto_merge_eligible(rule_id):
                merged = merge_pull_request(link["repo_url"], link["access_token"], pr["number"])
                step("Auto-merge", merged, "merged into " + link["default_branch"] if merged else "Merge failed — merge it manually")
                result["merged"] = merged

        return result

    except subprocess.CalledProcessError as e:
        logger.exception("Auto-fix subprocess failed")
        step("Pipeline", False, (e.stderr or str(e))[-500:])
        return {"status": "failed", "steps": steps, "error": "A build/git step failed"}
    except Exception as e:
        logger.exception("Auto-fix failed")
        step("Pipeline", False, str(e))
        return {"status": "failed", "steps": steps, "error": str(e)}
    finally:
        if repo_dir and repo_dir.exists():
            _rmtree_force(repo_dir)
